### ISSUE TITLE
Where is controller.js file??

### ISSUE THREAD

**Issue by mean-jugal** [giorgiofellipe/ionic-parse-facebook-auth#3]

**Comment by giorgiofellipe** [comment]
All the controllers are inside the `app.js` file. It was built to be an example on how to use facebook authentication, so this doesn't include good practices on developing Ionic apps.

**Comment by mean-jugal** [comment]
Then why code added in index.html [script src="js/controllers.js"][/script]

**Comment by giorgiofellipe** [comment]
It shouldn't be loaded, thanks.
